server:
  port: 8001
  servlet:
    context-path: /

spring:
  datasource:
    initialization-mode: always
  data:
    mongodb:
      uri: "${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/}"
      database: "${SPRING_DATA_MONGODB_DATABASE:java-test-project}"
  rabbitmq:
    host: "${SPRING_RABBITMQ_HOST:localhost}"
    port: "${SPRING_RABBITMQ_PORT:5672}"
    username: "${SPRING_RABBITMQ_USERNAME:guest}"
    password: "${SPRING_RABBITMQ_PASSWORD:guest}"
my:
  app:
    pass_smtp: "${PASS_SMTP}"

# Used for test, it logs queries
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
              MongoTemplate: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE